= Android Internals Training

24 February 2014

*Marius Mailat*, +<marius.mailat@gmail.com>+
http://thewnewcircle.com[The New Circle, Inc.]

== Obtaining Course Materials

You can either clone this Git repository:

  git clone git://github.com/mailat/bootcamp-2014-02-24.git

or

   download a Zip archive by clicking the link at the top of the page or using the link:
  
	https://github.com/mailat/bootcamp-2014-02-24/zipball/master

== Useful Links

Git book: http://git-scm.com/book

Marakana Java Fundamentals Tutorial: http://marakana.com/bookshelf/java_fundamentals_tutorial/index.html

Introduction to Eclipse - Driving Java Productivity: http://mrkn.co/s/video_introduction_to_eclipse_driving_java_productivity,595/index.html

Java Tutorial http://docs.oracle.com/javase/tutorial/

Android 4 KitKat changes for marakana-alpha are located at: https://github.com/thenewcircle/alpha/tree/kitkat-dev

Amazon source code for Kindle tablet is located at - http://www.amazon.com/gp/help/customer/display.html?nodeId=200203720

== Homework Day 01

1. Change title of the Browser app in "Novosibirk Browser"
2. Add support in alpha for an only RU, EN board

For extra 100 RUB points:

3. Change the button default color text in RED :)

== Homework Day 02

1. Read the multiuser information at page: NewCircle_Android_Internals.html#slide-134 . 

Activate multiuser on your emulator phone!

Try to use overlay to do the following, activate multiuser on your emulator ( tip: you need beside the value config_multiuserMaximumUsers=>8 also to overlay an landscape layout keyguard_host_view.xml ).

2. Try to remove from your distribution an app like Browser.

== Homework Day 03

1. Display in status bar HSPA distinct from UMTS data icon on devices
2. Change the default screen timeout to 30 seconds
3. Set the automatic brightness mode on by default 
4. Change the default screen brightness to 36%

